### ISSUE TITLE
[Bug] Project ERROR while compiling static qt framework

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/remote-ui#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When trying to compile a static qt framework on macOS 14.1 I get stuck at step 4:

```
~/Qt/5.15.2/Src/configure --prefix=~/Qt/5.15.2/clang_64-static -static -debug-and-release \                          projects/qt-static-5.15.2 18:13:00
    -nomake examples -nomake tests \
    -qt-libpng -qt-zlib -qt-libjpeg \
    -opensource -confirm-license \
    -opengl -qt-freetype -qt-pcre -qt-harfbuzz -platform macx-clang
+ cd qtbase
+ /Users/kenny/Qt/5.15.2/Src/qtbase/configure -top-level --prefix=~/Qt/5.15.2/clang_64-static -static -debug-and-release -nomake examples -nomake tests -qt-libpng -qt-zlib -qt-libjpeg -opensource -confirm-license -opengl -qt-freetype -qt-pcre -qt-harfbuzz -platform macx-clang
Preparing build tree...
Creating qmake...
...................................................................................................Done.
Info: creating super cache file /Users/kenny/projects/qt-static-5.15.2/.qmake.super
Info: creating cache file /Users/kenny/projects/qt-static-5.15.2/.qmake.cache
Info: creating stash file /Users/kenny/projects/qt-static-5.15.2/.qmake.stash
Project ERROR: failed to parse default search paths from compiler output
```

Output with -v:
[verbose.txt](https://github.com/unfoldedcircle/remote-ui/files/13219614/verbose.txt)

### How to Reproduce

1. Follow the instructions mentioned here https://github.com/unfoldedcircle/remote-ui/blob/main/docs/static-compile.md

### Expected behavior

There should be no error at the end

**Comment by zehnm** [comment]
The last major Xcode SDK version 14 update for macOS 14 broke qmake on macOS 13.
We are also not running macOS 14 yet, usually they break too many things with new major releases...
Anyhow, there's not much we can do here, it's a Qt / Apple issue.

This is how we fixed the Xcode update:
- patch the generated `.qmake.stash`
- add the missing pathes which were there before Xcode was updated:

Diff from the old .qmake.stash file:
```
> QMAKE_CXX.INCDIRS = \
>     /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 \
>     /Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include \
>     /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include \
>     /Library/Developer/CommandLineTools/usr/include
> QMAKE_CXX.LIBDIRS = /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
> QMAKE_MAC_SDK.macosx.SDKVersion = 13.3
> QMAKE_MAC_SDK.macosx.Path = /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
> QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTool
```

Add those to the newly generated file, and adapt clang directories and SDKVersion.

As a reference, my full file looks like this, it might or might not work on another installation or macOS 14!
```

QMAKE_MAC_SDK.macosx.Path = /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
QMAKE_MAC_SDK.macosx.SDKVersion = 14.0
QMAKE_MAC_SDK.macx-clang.macosx.QMAKE_CC = /Library/Developer/CommandLineTools/usr/bin/clang
QMAKE_MAC_SDK.macx-clang.macosx.QMAKE_CXX = /Library/Developer/CommandLineTools/usr/bin/clang++
QMAKE_MAC_SDK.macx-clang.macosx.QMAKE_FIX_RPATH = \
    /Library/Developer/CommandLineTools/usr/bin/install_name_tool \
    -id
QMAKE_MAC_SDK.macx-clang.macosx.QMAKE_AR = \
    /Library/Developer/CommandLineTools/usr/bin/ar \
    cq
QMAKE_MAC_SDK.macx-clang.macosx.QMAKE_RANLIB = \
    /Library/Developer/CommandLineTools/usr/bin/ranlib \
    -s
QMAKE_MAC_SDK.macx-clang.macosx.QMAKE_LINK = /Library/Developer/CommandLineTools/usr/bin/clang++
QMAKE_MAC_SDK.macx-clang.macosx.QMAKE_LINK_SHLIB = /Library/Developer/CommandLineTools/usr/bin/clang++
QMAKE_MAC_SDK.macx-clang.macosx.QMAKE_LINK_C = /Library/Developer/CommandLineTools/usr/bin/clang
QMAKE_MAC_SDK.macx-clang.macosx.QMAKE_LINK_C_SHLIB = /Library/Developer/CommandLineTools/usr/bin/clang
QMAKE_CXX.QT_COMPILER_STDCXX = 199711L
QMAKE_CXX.QMAKE_APPLE_CC = 6000
QMAKE_CXX.QMAKE_APPLE_CLANG_MAJOR_VERSION = 15
QMAKE_CXX.QMAKE_APPLE_CLANG_MINOR_VERSION = 0
QMAKE_CXX.QMAKE_APPLE_CLANG_PATCH_VERSION = 0
QMAKE_CXX.QMAKE_GCC_MAJOR_VERSION = 4
QMAKE_CXX.QMAKE_GCC_MINOR_VERSION = 2
QMAKE_CXX.QMAKE_GCC_PATCH_VERSION = 1
QMAKE_CXX.COMPILER_MACROS = \
    QT_COMPILER_STDCXX \
    QMAKE_APPLE_CC \
    QMAKE_APPLE_CLANG_MAJOR_VERSION \
    QMAKE_APPLE_CLANG_MINOR_VERSION \
    QMAKE_APPLE_CLANG_PATCH_VERSION \
    QMAKE_GCC_MAJOR_VERSION \
    QMAKE_GCC_MINOR_VERSION \
    QMAKE_GCC_PATCH_VERSION
QMAKE_CXX.INCDIRS = \
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 \
    /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include \
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include \
    /Library/Developer/CommandLineTools/usr/include
QMAKE_CXX.LIBDIRS = /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
```

There's a good chance that there's an easier fix, but that worked for us.

**If anyone knows a better solution, then please let us know.**

**Comment by kennymc-c** [comment]
I tried it by manual adding and adapt the diff to the stash file and also by replacing it with the reference but both result in this error:

```
Running configuration tests...
Checking for valid makespec... ERROR: Cannot compile a minimal program. The toolchain or QMakeSpec is broken.

Check config.log for details.
```

[config.log](https://github.com/unfoldedcircle/remote-ui/files/13220338/config.log)

**Comment by zehnm** [comment]
A quick Google search about the SDK 14 issue turned up a proper fix for `toolchain.prf`:

- https://stackoverflow.com/questions/77136519/qmake-failing-with-sdk-14-ventura-13-5-2
- https://forum.qt.io/topic/149758/macos-project-error-failed-to-parse-default-search-paths-from-compiler-output
- https://bugreports.qt.io/browse/QTBUG-117225
- https://codereview.qt-project.org/c/qt/qtbase/+/503172/3/mkspecs/features/toolchain.prf

Not verified, but seems to be the proper fix.

---

Closing issue: verified with the manually patched .qmake.stash as described in previous comment on macOS 13.6 with SDK 14 ✅

Step 4) configure:
```
mzehnder@DevMachine projects % mkdir -p ~/projects/qt-static-5.15.2
cd ~/projects/qt-static-5.15.2
mzehnder@DevMachine qt-static-5.15.2 % ~/Qt/5.15.2/Src/configure --prefix=~/Qt/5.15.2/clang_64-static -static -debug-and-release \
    -nomake examples -nomake tests \
    -qt-libpng -qt-zlib -qt-libjpeg \
    -opensource -confirm-license \
    -opengl -qt-freetype -qt-pcre -qt-harfbuzz -platform macx-clang
+ cd qtbase
+ /Users/mzehnder/Qt/5.15.2/Src/qtbase/configure -top-level --prefix=~/Qt/5.15.2/clang_64-static -static -debug-and-release -nomake examples -nomake tests -qt-libpng -qt-zlib -qt-libjpeg -opensource -confirm-license -opengl -qt-freetype -qt-pcre -qt-harfbuzz -platform macx-clang
Preparing build tree...
Creating qmake...
...................................................................................................Done.
Info: creating super cache file /Users/mzehnder/projects/qt-static-5.15.2/.qmake.super
Info: creating cache file /Users/mzehnder/projects/qt-static-5.15.2/.qmake.cache
Info: creating stash file /Users/mzehnder/projects/qt-static-5.15.2/.qmake.stash
Project ERROR: failed to parse default search paths from compiler output
mzehnder@DevMachine qt-static-5.15.2 % ll
total 32
drwxr-xr-x   8 mzehnder  wheel   256B Oct 31 22:30 .
drwxr-xr-x  14 mzehnder  wheel   448B Oct 31 22:28 ..
-rw-r--r--   1 mzehnder  wheel     1B Oct 31 22:29 .config.notes
-rw-r--r--   1 mzehnder  wheel    22B Oct 31 22:30 .qmake.cache
-rw-r--r--   1 mzehnder  wheel   1.6K Oct 31 22:30 .qmake.stash
-rw-r--r--   1 mzehnder  wheel     0B Oct 31 22:30 .qmake.super
-rw-r--r--   1 mzehnder  wheel   236B Oct 31 22:30 config.log
drwxr-xr-x   5 mzehnder  wheel   160B Oct 31 22:29 qtbase
mzehnder@DevMachine qt-static-5.15.2 % cp .qmake.stash .qmake.stash.generated
mzehnder@DevMachine qt-static-5.15.2 % nano .qmake.stash
mzehnder@DevMachine qt-static-5.15.2 % diff .qmake.stash.generated .qmake.stash
34a35,41
> QMAKE_CXX.INCDIRS = \
>     /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 \
>     /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include \
>     /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include \
>     /Library/Developer/CommandLineTools/usr/include
> QMAKE_CXX.LIBDIRS = /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
> QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
```

Then the configuration steps succeeds: 
[sdk14_configure.log](https://github.com/unfoldedcircle/remote-ui/files/13221829/sdk14_configure.log)


Step 5) Building

With SDK 14 or a newer macOS we run into a further compile error:
```
ui_qfiledialog.h Symbol not found: __ZTVNSt3__13pmr25monotonic_buffer_resourceE
```

Google search again: it's a known bug with a patch https://codereview.qt-project.org/c/qt/qtbase/+/482392

Patchfile for Qt 5.15 instead of the confusing qt-project.org site:
https://github.com/bitcoin/bitcoin/blob/5a4eb56e3fc47fd44dd2efbc55509d0663f9a47c/depends/patches/qt/memory_resource.patch

Download and apply:
cd ~/Qt/5.15.2/Src 
patch -p1 -i memory_resource.patch 

Then continue with step 5: 
```
make -j 10
```

Build succeeds ✅

**Comment by kennymc-c** [comment]
Thanks for your help. But I still can't build the app in Qt Creator. I installed everything including the virtualkeyboard plugin but I still get this compile error:
`ld: library 'qtvirtualkeyboardplugin' not found`
Two things I noticed: The 3rd-party/QR-Code-generator folder is empty when you clone the repo. I had to manually download the other repo and paste it into the folder otherwise I get another compile error.
The static framework is creating a folder structure inside the projects folder called ~/Qt/5.15.2/ instead of using the Qt folder inside user directory. I tried to copy the clang_64-static folder to the real ~/Qt/5.15.2/ directory but this dissent seem to make a difference when building the app.

Maybe you could just provide the macOS binary app in this repository so users without Qt knowledge can use it as an alternative to the linux VM image?

**Comment by zehnm** [comment]
> Two things I noticed: The 3rd-party/QR-Code-generator folder is empty when you clone the repo.

This is a [Git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules)! See `.gitmodules`, or the [GitHub build action]().
```console
git submodule update --init --recursive
```
There are no manual copy steps required.

If you use the remote-ui app for local development only, you don't need the static Qt build. This is only for running the app on other systems without the Qt installation.
